language: go
go:
  - 1.12.2
sudo: false
dist: xenial

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.5/hugo_extended_0.55.5_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0

script:
  - hugo -v

deploy:
  provider: pages
  local_dir: public
  repo: crevax/crevax.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: www.cjdavis.me
  on:
    branch: master
